webtalk_init -webtalk_dir C:/Users/7376247/Desktop/CENG342/lab03/lab_03/lab_03.sim/sim_1/behav/xsim/xsim.dir/Two_One_Mux_Bench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 11 12:13:57 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211874734_0_0_845" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2b6605a6-6ccc-415b-844a-ba1af6aa7ab2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "70a058266d0a4cc3aefda377b9adff67" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5864_KB" -context "xsim\\usage"
webtalk_transmit -clientid 869113911 -regid "211874734_0_0_845" -xml C:/Users/7376247/Desktop/CENG342/lab03/lab_03/lab_03.sim/sim_1/behav/xsim/xsim.dir/Two_One_Mux_Bench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/7376247/Desktop/CENG342/lab03/lab_03/lab_03.sim/sim_1/behav/xsim/xsim.dir/Two_One_Mux_Bench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/7376247/Desktop/CENG342/lab03/lab_03/lab_03.sim/sim_1/behav/xsim/xsim.dir/Two_One_Mux_Bench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
