@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Apr 07 03:49:14 -0500 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 2b333a0b00e04804892e4ce8cab76316 --incr --debug typical --relax --mt 2 -L work -L secureip --snapshot ccr_test_bench_behav work.ccr_test_bench -log elaborate.log"
call xelab  -wto 2b333a0b00e04804892e4ce8cab76316 --incr --debug typical --relax --mt 2 -L work -L secureip --snapshot ccr_test_bench_behav work.ccr_test_bench -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
