@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon May 04 20:21:29 -0500 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto eec409bfc6a34e74949dbf561b8e6c4f --incr --debug typical --relax --mt 2 -L work -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot ALU_Testbench_behav work.ALU_Testbench work.glbl -log elaborate.log"
call xelab  -wto eec409bfc6a34e74949dbf561b8e6c4f --incr --debug typical --relax --mt 2 -L work -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot ALU_Testbench_behav work.ALU_Testbench work.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
