@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Apr 09 20:11:50 -0600 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto d2bed9958c2b4206b62bc1d8d6c4b53d --incr --debug typical --relax --mt 2 -L work -L xil_defaultlib -L secureip --snapshot BTU_test_behav xil_defaultlib.BTU_test -log elaborate.log"
call xelab  -wto d2bed9958c2b4206b62bc1d8d6c4b53d --incr --debug typical --relax --mt 2 -L work -L xil_defaultlib -L secureip --snapshot BTU_test_behav xil_defaultlib.BTU_test -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
